# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xe5_A4vLl655Zg9O0mnyEAddSn4Km48n
"""

#NLP Project (Pipeline -> Text Cleaning)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('train.txt',sep=';',header=None, names=['text','emotions']) #in csv file we dont have comas so
#what we did here is we read our txt file as csv file and separated it with the comas
#and created two cols text and emotions

df.head()

df.isnull().sum() #to check whether we have null values or not

#now checking how many unique emotions we have
df['emotions'].unique()

#now creating a dictionory where these emotions are converted into 0 based indexing
unique_emotions= df['emotions'].unique() #first created a array
emotion_numbers={}
i=0
for emo in unique_emotions:
    emotion_numbers[emo]=i
    i=i+1
df['emotions']=df['emotions'].map(emotion_numbers)

df

#converting all texts in lower case
df['text'] = df['text'].apply(lambda x: x.lower())
df

#Removing punctuations
import string
def remove_punc(txt):
  return txt.translate(str.maketrans('','',string.punctuation))
df['text'] = df['text'].apply(remove_punc)

# Remove numbers
def remove_num(txt):
  new=""
  for i in txt:
    if not i.isdigit():
      new=new+i
  return new
df['text'] = df['text'].apply(remove_num)

# Remove emogis and special char
def remove_emojis(txt):
  new=""
  for i in txt:
    if i.isascii(): # move data to new only if i has a ascii value and as emojis dont have any ascii value it will be terminated
      new=new+i
  return new
df['text'] = df['text'].apply(remove_emojis)

# Remove stopwords
# to remove the stopwords we have to use a library and that is NLTK
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
nltk.download('stopwords')
nltk.download('punkt')# is a library which toeknizes your words (means simply , it is used for tokenization)

# to see the set of stopwords
stop_words = set(stopwords.words('english'))
stop_words

len(stop_words)

#now removing stop words
df.loc[1]['text'] # to see the data

# as we have the list of stop words and will convert it into array
def remove(txt):
  words = txt.split() #here we have to use word_tokenize instead of split (we are using split as it is giving some error in google colab)
  cleaned = []
  for i in words:
    if not i in stop_words:
      cleaned.append(i)
  return ' '.join(cleaned)
df['text'] = df['text'].apply(remove)
# note: split and tokenize are both diff

# now seeing the same sentence after removing stopwords
df.loc[1]['text']

# This is all about data preprocessing in NLP

# now heading to the project

df.head()

#doing train_test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df['text'],df['emotions'],test_size=0.2,random_state=42)

X_train

X_test

# vectorization (converting x_train and x_test into vectors)
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

#first doing with count vectorizer(bag of words)
cv = CountVectorizer()
X_train_cv = cv.fit_transform(X_train)
X_test_cv = cv.transform(X_test)

from sklearn.naive_bayes import MultinomialNB # for text classification we use Myultinomial Naive Bayes algo
from sklearn.metrics import accuracy_score
model = MultinomialNB()
model.fit(X_train_cv,y_train)

y_pred = model.predict(X_test_cv)
print(accuracy_score(y_test,y_pred))

y_pred

# now doing with TF-IDF
cv = TfidfVectorizer()
X_train_cv = cv.fit_transform(X_train)
X_test_cv = cv.transform(X_test)

model = MultinomialNB() # for text classification we use Myultinomial Naive Bayes algo
model.fit(X_train_cv,y_train)

y_pred = model.predict(X_test_cv)
print(accuracy_score(y_test,y_pred))

# doing TF-IDF With logistic regression

from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=1000)
model.fit(X_train_cv,y_train)

y_pred = model.predict(X_test_cv)
print(accuracy_score(y_test,y_pred))

# this is all about this project